# Generated by Django 3.1.2 on 2020-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='사진'),
        ),
    ]
