# Generated by Django 3.1.2 on 2020-11-14 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_auto_20201114_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='memo.memo'),
        ),
    ]
